import os
from pathlib import Path

UDP_PORT = 4210
BROADCAST_ADDR = "255.255.255.0"
DEVICE_TIMEOUT_SECONDS = 30
CLEANUP_INTERVAL_SECONDS = 10
PROXY_DEFAULT_PORT = 80
PROXY_TIMEOUT_SECONDS = 10
NODES_FILE = Path(os.environ.get("NODES_FILE", "data/nodes.json"))
